---
# tasks file for /etc/ansible/roles/wpusers

  - name: Copy users list file to database server
    copy: 
       src: files/user_list 
       dest: /tmp/user_list
       owner: root
       group: root
       mode: 0644

  - name: Copy bash script to database server
    copy: 
       src: files/script.sh 
       dest: /tmp/script.sh 
       owner: root
       group: root
       mode: 0755

  - name: Make SQL command file
    shell: /tmp/script.sh
    args:
       creates: /tmp/user_add.sql

  - name: Run user_add.sql to add WordPress users
    shell: mysql -u wordpress -pTh@W0rd1u*GH9 -D wordpress < /tmp/user_add.sql 2> /dev/null

  - name: Remove files from /tmp
    file: 
        path: "{{ item }}"
        state: absent
    with_items:
        - /tmp/user_list
        - /tmp/user_add.sql
        - /tmp/script.sh
