---
# tasks file for /etc/ansible/roles/database
  - name: Install MySQL
    apt: 
       name: mysql-server 
       state: installed 
       update-cache: yes

  - name: Install MySQL-python module
    apt: 
       name: python-mysqldb 
       state: installed 

  - name: Restart MySQL
    service: 
       name: mysql 
       state: restarted 
       enabled: yes

  - name: Create mysql database
    mysql_db: 
       name: "{{ wp_mysql_db }}" 
       state: present

  - name: Create mysql user
    mysql_user: 
       name: "{{ wp_mysql_user }}" 
       password: "{{ wp_mysql_password }}" 
       priv: '*.*:ALL'
       state: present

  - name: Override localhost option for mysql user
    mysql_user: 
       name: "{{ wp_mysql_user }}" 
       password: "{{ wp_mysql_password }}" 
       host_all: yes
       state: present

  - name: Edit mysql config file - comment out 'skip-external-locking'
    replace:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^skip-external-locking'
        replace: '#skip-external-locking'

  - name: Edit mysql config file - comment out 'bind-address=127.0.0.1'
    replace:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        replace: '#bind-address'

  - name: Restart MySQL
    service: 
       name: mysql 
       state: restarted 
